sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t appymango/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true appymango/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-south-1-469669170709"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
