name: Deploy Frontend
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image & Run Tests
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t appymango/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true appymango/docker-react npm test
      ## Create Build
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      ## Deploy Build to AWS Elastic Bean Stalk
      - name: Deploy to AWS Elastic Bean Stalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-469669170709
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
