name: Deploy Frontend
on:
  push:
    branches:
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image & Run Tests
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t appymango/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true appymango/docker-react npm test
