# Run Tests on Branch - Feature
name: Run Tests
on:
  push:
    branches:
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Build Image & Run Tests
      - uses: actions/checkout@v2
      # Authorize Docker with Access Token
      - name: Authorize Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Build Image
      - name: Build Image
        run: docker build -t appymango/docker-react -f Dockerfile.dev .
      # Run Tests
      - name: Run Tests
        run: docker run -e CI=true appymango/docker-react npm test
